package slu.model;
// Generated 20/11/2016 21:31:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contato generated by hbm2java
 */
public class Contato  implements java.io.Serializable {


     private int id;
     private String cep;
     private String endereco;
     private Integer numero;
     private String complemento;
     private String bairro;
     private String cidade;
     private String uf;
     private String telefone;
     private String email;
     private Set usuarios = new HashSet(0);
     private Set universidadeses = new HashSet(0);

    public Contato() {
    }

	
    public Contato(int id) {
        this.id = id;
    }
    public Contato(int id, String cep, String endereco, Integer numero, String complemento, String bairro, String cidade, String uf, String telefone, String email, Set usuarios, Set universidadeses) {
       this.id = id;
       this.cep = cep;
       this.endereco = endereco;
       this.numero = numero;
       this.complemento = complemento;
       this.bairro = bairro;
       this.cidade = cidade;
       this.uf = uf;
       this.telefone = telefone;
       this.email = email;
       this.usuarios = usuarios;
       this.universidadeses = universidadeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getUniversidadeses() {
        return this.universidadeses;
    }
    
    public void setUniversidadeses(Set universidadeses) {
        this.universidadeses = universidadeses;
    }




}


